trigger:
  - lab

parameters:
  - name: deliveryTrain
    type: object
    default:
      continuousTesting:
        - environment: none
          cases:
            - type: service
              with: serenity
              timeoutInMinutes: 120
              agentName: linux-generic
              sonarQube:
                serviceConnection: sc-az-solucionescorporativas-pdn_eefce279-9b08-4687-a872-762a8e311aed
                sonarProjectFile: $(System.DefaultWorkingDirectory)/testaceptacion/sonar-project.properties
              configure:
                repo:
                  name: Gerencia_Tecnologia/1212-apiarchivodigitalp8_cachep8-pa
                  branch: lab
                visualTestsCommand: clean build test -DTiporegresion=$(Tiporegresion) aggregate --parallel --max-workers=2
                visualTestsReportDir: 'testaceptacion/target/site/serenity/'
                visualTestsWorkingDir: $(System.DefaultWorkingDirectory)/testaceptacion
                workingDirectory: $(System.DefaultWorkingDirectory)/testaceptacion
                javaVersion: 17
resources:
  repositories:
    - repository: templates
      type: git
      name: Gerencia_Tecnologia/ti-templates_pipelines-conf
      ref: master

extends:
  template: templates/template-pa.yaml@templates
  parameters:
    deliveryTrain: ${{ parameters.deliveryTrain }}    